version: "3"
## docker-compose up [--build] to force it build a new image after changes
services:
  # name of the service
  api:
    build: .
    depends_on:
      - postgres
    ports:
      # this forwards port requests to the container
      # format: <local port>:<port on container>
      - 8000:8000
    #env_file:
    #  - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABSE_PASSWORD=postgres123
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db: /var/lib/postgresql/data

volumes:
  postgres-db: